# Generated by Django 4.2.1 on 2023-06-10 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriterecipes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Szamapp.user'),
        ),
    ]
