# Generated by Django 4.2.1 on 2023-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0005_favouriterecipes_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='MealBaseOptions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=8192),
        ),
    ]
