# Generated by Django 4.2.1 on 2023-07-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0006_delete_chat_delete_mealbaseoptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecipes',
            old_name='user_id',
            new_name='user',
        ),
    ]
