# Generated by Django 4.2.1 on 2023-07-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0007_rename_user_id_favouriterecipes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriterecipes',
            name='user',
        ),
    ]
