# Generated by Django 4.2.1 on 2023-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0008_remove_favouriterecipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriterecipes',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='statistics',
            name='recipes',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='statistics',
            name='users',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
