# Generated by Django 4.2.3 on 2023-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szamapp', '0010_delete_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.IntegerField(null=True)),
                ('users', models.IntegerField(null=True)),
            ],
        ),
    ]
